import { Word, LearningSet, UserLevel } from './types';

export const vocabularyData: Word[] = [
  // Базовые глаголы (Basis-Verben)
  { id: 'v001', russian: 'быть', german: 'sein', ipa: '[zaɪ̯n]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich bin Anna.', ru: 'Я Анна.' }, { de: 'Das ist ein Buch.', ru: 'Это книга.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v002', russian: 'иметь', german: 'haben', ipa: '[ˈhaːbən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich habe ein Buch.', ru: 'У меня есть книга.' }, { de: 'Du hast Zeit.', ru: 'У тебя есть время.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v003', russian: 'идти, ходить', german: 'gehen', ipa: '[ˈɡeːən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich gehe zur Schule.', ru: 'Я иду в школу.' }, { de: 'Wir gehen spazieren.', ru: 'Мы идём гулять.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v004', russian: 'делать', german: 'machen', ipa: '[ˈmaxən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich mache Hausaufgaben.', ru: 'Я делаю домашнее задание.' }, { de: 'Was machst du?', ru: 'Что ты делаешь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v005', russian: 'говорить', german: 'sprechen', ipa: '[ˈʃpʁɛçən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich spreche Deutsch.', ru: 'Я говорю по-немецки.' }, { de: 'Sprichst du Englisch?', ru: 'Ты говоришь по-английски?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v006', russian: 'есть, кушать', german: 'essen', ipa: '[ˈɛsən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich esse Brot.', ru: 'Я ем хлеб.' }, { de: 'Was isst du?', ru: 'Что ты ешь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v007', russian: 'пить', german: 'trinken', ipa: '[ˈtʁɪŋkən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich trinke Wasser.', ru: 'Я пью воду.' }, { de: 'Er trinkt Kaffee.', ru: 'Он пьёт кофе.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v008', russian: 'работать', german: 'arbeiten', ipa: '[ˈaʁbaɪ̯tən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich arbeite viel.', ru: 'Я много работаю.' }, { de: 'Sie arbeitet als Ärztin.', ru: 'Она работает врачом.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v009', russian: 'учиться', german: 'lernen', ipa: '[ˈlɛʁnən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich lerne Deutsch.', ru: 'Я учу немецкий.' }, { de: 'Wir lernen zusammen.', ru: 'Мы учимся вместе.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v010', russian: 'читать', german: 'lesen', ipa: '[ˈleːzən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich lese ein Buch.', ru: 'Я читаю книгу.' }, { de: 'Er liest die Zeitung.', ru: 'Он читает газету.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v011', russian: 'писать', german: 'schreiben', ipa: '[ˈʃʁaɪ̯bən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich schreibe einen Brief.', ru: 'Я пишу письмо.' }, { de: 'Schreib deinen Namen!', ru: 'Напиши своё имя!' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'v012', russian: 'знать', german: 'wissen', ipa: '[ˈvɪsən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich weiß es nicht.', ru: 'Я не знаю.' }, { de: 'Weißt du das?', ru: 'Ты это знаешь?' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Семья (Familie)
  { id: 'n001', russian: 'мать', german: 'die Mutter', ipa: '[ˈmʊtɐ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Mutter heißt Maria.', ru: 'Мою мать зовут Мария.' }, { de: 'Die Mutter arbeitet.', ru: 'Мать работает.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n002', russian: 'отец', german: 'der Vater', ipa: '[ˈfaːtɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Mein Vater ist Arzt.', ru: 'Мой отец врач.' }, { de: 'Der Vater liest.', ru: 'Отец читает.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n003', russian: 'сестра', german: 'die Schwester', ipa: '[ˈʃvɛstɐ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Schwester ist Lehrerin.', ru: 'Моя сестра учительница.' }, { de: 'Die Schwester studiert.', ru: 'Сестра учится.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n004', russian: 'брат', german: 'der Bruder', ipa: '[ˈbʁuːdɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Mein Bruder spielt Fußball.', ru: 'Мой брат играет в футбол.' }, { de: 'Der Bruder ist jung.', ru: 'Брат молодой.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n005', russian: 'ребёнок', german: 'das Kind', ipa: '[kɪnt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Kind spielt.', ru: 'Ребёнок играет.' }, { de: 'Wir haben zwei Kinder.', ru: 'У нас двое детей.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n006', russian: 'семья', german: 'die Familie', ipa: '[faˈmiːliə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Familie ist groß.', ru: 'Моя семья большая.' }, { de: 'Die Familie wohnt in Berlin.', ru: 'Семья живёт в Берлине.' }], category: 'Семья', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Дом (Haus)
  { id: 'n007', russian: 'дом', german: 'das Haus', ipa: '[haʊ̯s]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Haus ist groß.', ru: 'Дом большой.' }, { de: 'Ich lebe in einem Haus.', ru: 'Я живу в доме.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n008', russian: 'комната', german: 'das Zimmer', ipa: '[ˈtsɪmɐ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Zimmer ist hell.', ru: 'Комната светлая.' }, { de: 'Ich schlafe im Zimmer.', ru: 'Я сплю в комнате.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n009', russian: 'кухня', german: 'die Küche', ipa: '[ˈkʏçə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Küche ist sauber.', ru: 'Кухня чистая.' }, { de: 'Ich koche in der Küche.', ru: 'Я готовлю на кухне.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n010', russian: 'стол', german: 'der Tisch', ipa: '[tɪʃ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Tisch ist rund.', ru: 'Стол круглый.' }, { de: 'Ich sitze am Tisch.', ru: 'Я сижу за столом.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n011', russian: 'стул', german: 'der Stuhl', ipa: '[ʃtuːl]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Stuhl ist bequem.', ru: 'Стул удобный.' }, { de: 'Setz dich auf den Stuhl!', ru: 'Сядь на стул!' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n012', russian: 'кровать', german: 'das Bett', ipa: '[bɛt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Bett ist weich.', ru: 'Кровать мягкая.' }, { de: 'Ich liege im Bett.', ru: 'Я лежу в кровати.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Еда (Essen)
  { id: 'n013', russian: 'хлеб', german: 'das Brot', ipa: '[bʁoːt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Brot ist frisch.', ru: 'Хлеб свежий.' }, { de: 'Ich esse Brot zum Frühstück.', ru: 'Я ем хлеб на завтрак.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n014', russian: 'молоко', german: 'die Milch', ipa: '[mɪlç]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Milch ist kalt.', ru: 'Молоко холодное.' }, { de: 'Ich trinke Milch.', ru: 'Я пью молоко.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n015', russian: 'вода', german: 'das Wasser', ipa: '[ˈvasɐ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Wasser ist klar.', ru: 'Вода чистая.' }, { de: 'Ich trinke viel Wasser.', ru: 'Я пью много воды.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n016', russian: 'яблоко', german: 'der Apfel', ipa: '[ˈapfəl]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Apfel ist rot.', ru: 'Яблоко красное.' }, { de: 'Ich esse einen Apfel.', ru: 'Я ем яблоко.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n017', russian: 'кофе', german: 'der Kaffee', ipa: '[ˈkafe]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Kaffee ist heiß.', ru: 'Кофе горячий.' }, { de: 'Ich trinke Kaffee am Morgen.', ru: 'Я пью кофе утром.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Цвета (Farben)
  { id: 'a001', russian: 'красный', german: 'rot', ipa: '[ʁoːt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Auto ist rot.', ru: 'Машина красная.' }, { de: 'Sie trägt ein rotes Kleid.', ru: 'Она носит красное платье.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a002', russian: 'синий, голубой', german: 'blau', ipa: '[blaʊ̯]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Der Himmel ist blau.', ru: 'Небо голубое.' }, { de: 'Er hat blaue Augen.', ru: 'У него голубые глаза.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a003', russian: 'зелёный', german: 'grün', ipa: '[ɡʁyːn]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Gras ist grün.', ru: 'Трава зелёная.' }, { de: 'Ich mag grüne Äpfel.', ru: 'Мне нравятся зелёные яблоки.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a004', russian: 'чёрный', german: 'schwarz', ipa: '[ʃvaʁts]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Die Katze ist schwarz.', ru: 'Кошка чёрная.' }, { de: 'Er trägt schwarze Schuhe.', ru: 'Он носит чёрные туфли.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a005', russian: 'белый', german: 'weiß', ipa: '[vaɪ̯s]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Der Schnee ist weiß.', ru: 'Снег белый.' }, { de: 'Sie trägt ein weißes Hemd.', ru: 'Она носит белую рубашку.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Числа (Zahlen)
  { id: 'z001', russian: 'один', german: 'eins', ipa: '[aɪ̯ns]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe eins.', ru: 'У меня один.' }, { de: 'Eins plus eins ist zwei.', ru: 'Один плюс один равно два.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'z002', russian: 'два', german: 'zwei', ipa: '[tsvaɪ̯]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe zwei Katzen.', ru: 'У меня две кошки.' }, { de: 'Zwei Kinder spielen.', ru: 'Двое детей играют.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'z003', russian: 'три', german: 'drei', ipa: '[dʁaɪ̯]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe drei Bücher.', ru: 'У меня три книги.' }, { de: 'Es ist drei Uhr.', ru: 'Сейчас три часа.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Время (Zeit)
  { id: 't001', russian: 'сегодня', german: 'heute', ipa: '[ˈhɔʏ̯tə]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Heute ist Montag.', ru: 'Сегодня понедельник.' }, { de: 'Was machst du heute?', ru: 'Что ты делаешь сегодня?' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 't002', russian: 'завтра', german: 'morgen', ipa: '[ˈmɔʁɡən]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Morgen gehe ich ins Kino.', ru: 'Завтра я иду в кино.' }, { de: 'Bis morgen!', ru: 'До завтра!' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 't003', russian: 'вчера', german: 'gestern', ipa: '[ˈɡɛstɐn]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Gestern war es kalt.', ru: 'Вчера было холодно.' }, { de: 'Ich habe gestern gearbeitet.', ru: 'Вчера я работал.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 't004', russian: 'сейчас', german: 'jetzt', ipa: '[jɛtst]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Ich bin jetzt müde.', ru: 'Я сейчас устал.' }, { de: 'Jetzt lerne ich Deutsch.', ru: 'Сейчас я учу немецкий.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Город (Stadt)
  { id: 'n018', russian: 'город', german: 'die Stadt', ipa: '[ʃtat]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Stadt ist schön.', ru: 'Город красивый.' }, { de: 'Ich lebe in einer Stadt.', ru: 'Я живу в городе.' }], category: 'Город', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n019', russian: 'улица', german: 'die Straße', ipa: '[ˈʃtʁaːsə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Straße ist lang.', ru: 'Улица длинная.' }, { de: 'Ich wohne in der Hauptstraße.', ru: 'Я живу на главной улице.' }], category: 'Город', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n020', russian: 'магазин', german: 'der Laden', ipa: '[ˈlaːdən]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Laden ist offen.', ru: 'Магазин открыт.' }, { de: 'Ich gehe in den Laden.', ru: 'Я иду в магазин.' }], category: 'Город', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // A2 Wörter
  { id: 'v013', russian: 'понимать', german: 'verstehen', ipa: '[fɛɐ̯ˈʃteːən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich verstehe das nicht.', ru: 'Я не понимаю.' }, { de: 'Verstehst du mich?', ru: 'Ты меня понимаешь?' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'v014', russian: 'объяснять', german: 'erklären', ipa: '[ɛɐ̯ˈklɛːʁən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Kannst du das erklären?', ru: 'Ты можешь объяснить?' }, { de: 'Der Lehrer erklärt die Regel.', ru: 'Учитель объясняет правило.' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'v015', russian: 'помогать', german: 'helfen', ipa: '[ˈhɛlfən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Kannst du mir helfen?', ru: 'Ты можешь мне помочь?' }, { de: 'Ich helfe gerne.', ru: 'Я с удовольствием помогаю.' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'n021', russian: 'работа', german: 'die Arbeit', ipa: '[ˈaʁbaɪ̯t]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Arbeit ist interessant.', ru: 'Работа интересная.' }, { de: 'Ich suche eine Arbeit.', ru: 'Я ищу работу.' }], category: 'Работа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'n022', russian: 'деньги', german: 'das Geld', ipa: '[ɡɛlt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich habe kein Geld.', ru: 'У меня нет денег.' }, { de: 'Das Geld liegt auf dem Tisch.', ru: 'Деньги лежат на столе.' }], category: 'Работа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'n023', russian: 'время', german: 'die Zeit', ipa: '[tsaɪ̯t]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich habe keine Zeit.', ru: 'У меня нет времени.' }, { de: 'Die Zeit vergeht schnell.', ru: 'Время проходит быстро.' }], category: 'Время', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'a006', russian: 'большой', german: 'groß', ipa: '[ɡʁoːs]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Haus ist groß.', ru: 'Дом большой.' }, { de: 'Er ist sehr groß.', ru: 'Он очень высокий.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a007', russian: 'маленький', german: 'klein', ipa: '[klaɪ̯n]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Kind ist klein.', ru: 'Ребёнок маленький.' }, { de: 'Ich habe ein kleines Auto.', ru: 'У меня маленькая машина.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a008', russian: 'хороший', german: 'gut', ipa: '[ɡuːt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Essen ist gut.', ru: 'Еда хорошая.' }, { de: 'Er ist ein guter Freund.', ru: 'Он хороший друг.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a009', russian: 'плохой', german: 'schlecht', ipa: '[ʃlɛçt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Wetter ist schlecht.', ru: 'Погода плохая.' }, { de: 'Ich fühle mich schlecht.', ru: 'Я плохо себя чувствую.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'a010', russian: 'новый', german: 'neu', ipa: '[nɔʏ̯]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Ich habe ein neues Handy.', ru: 'У меня новый телефон.' }, { de: 'Das ist neu für mich.', ru: 'Это для меня ново.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // B1 Wörter
  { id: 'v016', russian: 'достигать', german: 'erreichen', ipa: '[ɛɐ̯ˈʁaɪ̯çən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich möchte mein Ziel erreichen.', ru: 'Я хочу достичь своей цели.' }, { de: 'Wir haben das Ziel erreicht.', ru: 'Мы достигли цели.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'v017', russian: 'решать', german: 'entscheiden', ipa: '[ɛntˈʃaɪ̯dən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich muss mich entscheiden.', ru: 'Мне нужно принять решение.' }, { de: 'Hast du dich entschieden?', ru: 'Ты уже решил?' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'n024', russian: 'возможность', german: 'die Möglichkeit', ipa: '[ˈmøːklɪçkaɪ̯t]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Das ist eine gute Möglichkeit.', ru: 'Это хорошая возможность.' }, { de: 'Ich habe keine Möglichkeit.', ru: 'У меня нет возможности.' }], category: 'Абстрактные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'n025', russian: 'опыт', german: 'die Erfahrung', ipa: '[ɛɐ̯ˈfaːʁʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich habe viel Erfahrung.', ru: 'У меня много опыта.' }, { de: 'Das war eine neue Erfahrung.', ru: 'Это был новый опыт.' }], category: 'Абстрактные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // B2 Wörter
  { id: 'v018', russian: 'предполагать', german: 'voraussetzen', ipa: '[foːɐ̯ˈaʊ̯szɛtsən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Das setzt Kenntnisse voraus.', ru: 'Это предполагает знания.' }, { de: 'Wir setzen Erfahrung voraus.', ru: 'Мы предполагаем наличие опыта.' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'n026', russian: 'обстоятельство', german: 'der Umstand', ipa: '[ˈʊmʃtant]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Unter diesen Umständen...', ru: 'При таких обстоятельствах...' }, { de: 'Das sind besondere Umstände.', ru: 'Это особые обстоятельства.' }], category: 'Абстрактные', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'n027', russian: 'последствие', german: 'die Konsequenz', ipa: '[kɔnzeˈkvɛnts]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Das hat Konsequenzen.', ru: 'Это имеет последствия.' }, { de: 'Ich ziehe die Konsequenzen.', ru: 'Я делаю выводы.' }], category: 'Абстрактные', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },

  // Природа (Natur)
  { id: 'n028', russian: 'солнце', german: 'die Sonne', ipa: '[ˈzɔnə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Sonne scheint.', ru: 'Солнце светит.' }, { de: 'Die Sonne ist heiß.', ru: 'Солнце горячее.' }], category: 'Природа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n029', russian: 'дождь', german: 'der Regen', ipa: '[ˈʁeːɡən]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Es regnet.', ru: 'Идёт дождь.' }, { de: 'Der Regen ist kalt.', ru: 'Дождь холодный.' }], category: 'Природа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n030', russian: 'дерево', german: 'der Baum', ipa: '[baʊ̯m]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Baum ist hoch.', ru: 'Дерево высокое.' }, { de: 'Unter dem Baum ist es kühl.', ru: 'Под деревом прохладно.' }], category: 'Природа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Тело (Körper)
  { id: 'n031', russian: 'голова', german: 'der Kopf', ipa: '[kɔpf]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Mein Kopf tut weh.', ru: 'У меня болит голова.' }, { de: 'Der Kopf ist rund.', ru: 'Голова круглая.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n032', russian: 'рука', german: 'die Hand', ipa: '[hant]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Gib mir deine Hand!', ru: 'Дай мне руку!' }, { de: 'Meine Hand ist kalt.', ru: 'Моя рука холодная.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n033', russian: 'глаз', german: 'das Auge', ipa: '[ˈaʊ̯ɡə]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich habe blaue Augen.', ru: 'У меня голубые глаза.' }, { de: 'Das Auge sieht alles.', ru: 'Глаз всё видит.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Транспорт (Transport)
  { id: 'n034', russian: 'машина', german: 'das Auto', ipa: '[ˈaʊ̯toː]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Auto ist schnell.', ru: 'Машина быстрая.' }, { de: 'Ich fahre mit dem Auto.', ru: 'Я еду на машине.' }], category: 'Транспорт', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n035', russian: 'поезд', german: 'der Zug', ipa: '[tsuːk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Zug kommt pünktlich.', ru: 'Поезд приходит вовремя.' }, { de: 'Ich fahre mit dem Zug.', ru: 'Я еду на поезде.' }], category: 'Транспорт', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'n036', russian: 'самолёт', german: 'das Flugzeug', ipa: '[ˈfluːktsɔʏ̯k]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Flugzeug fliegt hoch.', ru: 'Самолёт летит высоко.' }, { de: 'Ich fliege mit dem Flugzeug.', ru: 'Я лечу на самолёте.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
];

export const learningSets: LearningSet[] = [
  { id: 'set-001', name: 'Базовые глаголы', description: 'Самые важные немецкие глаголы для начинающих', category: 'Базовые глаголы', wordCount: 12, difficulty: 1, minUserLevel: 'beginner', icon: '🔤' },
  { id: 'set-002', name: 'Семья', description: 'Слова для описания членов семьи', category: 'Семья', wordCount: 6, difficulty: 1, minUserLevel: 'beginner', icon: '👨‍👩‍👧‍👦' },
  { id: 'set-003', name: 'Дом', description: 'Предметы домашнего обихода и комнаты', category: 'Дом', wordCount: 6, difficulty: 1, minUserLevel: 'beginner', icon: '🏠' },
  { id: 'set-004', name: 'Еда', description: 'Продукты питания и напитки', category: 'Еда', wordCount: 5, difficulty: 1, minUserLevel: 'beginner', icon: '🍎' },
  { id: 'set-005', name: 'Цвета', description: 'Основные цвета на немецком', category: 'Цвета', wordCount: 5, difficulty: 1, minUserLevel: 'beginner', icon: '🎨' },
  { id: 'set-006', name: 'Числа', description: 'Числа от 1 до 10 и далее', category: 'Числа', wordCount: 3, difficulty: 1, minUserLevel: 'beginner', icon: '🔢' },
  { id: 'set-007', name: 'Время', description: 'Слова для описания времени', category: 'Время', wordCount: 4, difficulty: 1, minUserLevel: 'beginner', icon: '⏰' },
  { id: 'set-008', name: 'Город', description: 'Места в городе и транспорт', category: 'Город', wordCount: 3, difficulty: 1, minUserLevel: 'beginner', icon: '🏙️' },
  { id: 'set-009', name: 'Прилагательные', description: 'Основные прилагательные', category: 'Прилагательные', wordCount: 5, difficulty: 1, minUserLevel: 'beginner', icon: '✨' },
  { id: 'set-010', name: 'Природа', description: 'Слова о природе и погоде', category: 'Природа', wordCount: 3, difficulty: 1, minUserLevel: 'beginner', icon: '🌿' },
  { id: 'set-011', name: 'Тело', description: 'Части тела', category: 'Тело', wordCount: 3, difficulty: 1, minUserLevel: 'beginner', icon: '🫀' },
  { id: 'set-012', name: 'Транспорт', description: 'Виды транспорта', category: 'Транспорт', wordCount: 3, difficulty: 1, minUserLevel: 'beginner', icon: '🚗' },
];

export function getWordsByUserLevel(level: UserLevel): Word[] {
  switch (level) {
    case 'beginner':
      return vocabularyData.filter(w => w.minUserLevel === 'beginner');
    case 'intermediate':
      return vocabularyData.filter(w => w.minUserLevel === 'beginner' || w.minUserLevel === 'intermediate');
    case 'advanced':
      return vocabularyData;
    default:
      return vocabularyData.filter(w => w.minUserLevel === 'beginner');
  }
}

export function getWordsByCategory(category: string): Word[] {
  return vocabularyData.filter(w => w.category === category);
}

export function getWordsByCEFR(level: string): Word[] {
  return vocabularyData.filter(w => w.cefrLevel === level);
}

// === Erweiterte Vokabeln (A1–B2) ===
const vocabularyDataOld: Word[] = [
  // Schule (Школа)
  { id: 'e001', russian: 'школа', german: 'die Schule', ipa: '[ˈʃuːlə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Schule beginnt um 8 Uhr.', ru: 'Школа начинается в 8 часов.' }, { de: 'Ich gehe zur Schule.', ru: 'Я иду в школу.' }], category: 'Школа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e002', russian: 'учитель', german: 'der Lehrer', ipa: '[ˈleːʁɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Lehrer erklärt die Aufgabe.', ru: 'Учитель объясняет задание.' }, { de: 'Mein Lehrer ist nett.', ru: 'Мой учитель добрый.' }], category: 'Школа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e003', russian: 'книга', german: 'das Buch', ipa: '[buːx]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Buch ist interessant.', ru: 'Книга интересная.' }, { de: 'Ich lese ein Buch.', ru: 'Я читаю книгу.' }], category: 'Школа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e004', russian: 'карандаш', german: 'der Bleistift', ipa: '[ˈblaɪ̯ʃtɪft]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich schreibe mit dem Bleistift.', ru: 'Я пишу карандашом.' }, { de: 'Der Bleistift ist kurz.', ru: 'Карандаш короткий.' }], category: 'Школа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e005', russian: 'ручка', german: 'der Stift', ipa: '[ʃtɪft]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Gib mir den Stift!', ru: 'Дай мне ручку!' }, { de: 'Der Stift schreibt gut.', ru: 'Ручка хорошо пишет.' }], category: 'Школа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Körper (Тело)
  { id: 'e006', russian: 'нога', german: 'das Bein', ipa: '[baɪ̯n]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Mein Bein tut weh.', ru: 'У меня болит нога.' }, { de: 'Das Bein ist lang.', ru: 'Нога длинная.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e007', russian: 'рот', german: 'der Mund', ipa: '[mʊnt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Mach den Mund auf!', ru: 'Открой рот!' }, { de: 'Der Mund ist groß.', ru: 'Рот большой.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e008', russian: 'нос', german: 'die Nase', ipa: '[ˈnaːzə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Nase ist kalt.', ru: 'Мой нос холодный.' }, { de: 'Die Nase ist rot.', ru: 'Нос красный.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Kleidung (Одежда)
  { id: 'e009', russian: 'рубашка', german: 'das Hemd', ipa: '[hɛmt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Hemd ist weiß.', ru: 'Рубашка белая.' }, { de: 'Ich trage ein Hemd.', ru: 'Я ношу рубашку.' }], category: 'Одежда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e010', russian: 'брюки', german: 'die Hose', ipa: '[ˈhoːzə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Hose ist blau.', ru: 'Брюки синие.' }, { de: 'Ich trage eine Hose.', ru: 'Я ношу брюки.' }], category: 'Одежда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e011', russian: 'обувь', german: 'die Schuhe', ipa: '[ˈʃuːə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Schuhe sind neu.', ru: 'Туфли новые.' }, { de: 'Ich kaufe neue Schuhe.', ru: 'Я покупаю новые туфли.' }], category: 'Одежда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e012', russian: 'куртка', german: 'die Jacke', ipa: '[ˈjakə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Jacke ist warm.', ru: 'Куртка тёплая.' }, { de: 'Ich ziehe die Jacke an.', ru: 'Я надеваю куртку.' }], category: 'Одежда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Tiere (Животные)
  { id: 'e013', russian: 'собака', german: 'der Hund', ipa: '[hʊnt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Hund bellt.', ru: 'Собака лает.' }, { de: 'Ich habe einen Hund.', ru: 'У меня есть собака.' }], category: 'Животные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e014', russian: 'кошка', german: 'die Katze', ipa: '[ˈkatsə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Katze schläft.', ru: 'Кошка спит.' }, { de: 'Meine Katze ist schwarz.', ru: 'Моя кошка чёрная.' }], category: 'Животные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e015', russian: 'птица', german: 'der Vogel', ipa: '[ˈfoːɡəl]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Vogel singt.', ru: 'Птица поёт.' }, { de: 'Der Vogel fliegt hoch.', ru: 'Птица летит высоко.' }], category: 'Животные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Verben A2 (Глаголы A2)
  { id: 'e016', russian: 'покупать', german: 'kaufen', ipa: '[ˈkaʊ̯fən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich kaufe Brot.', ru: 'Я покупаю хлеб.' }, { de: 'Was kaufst du?', ru: 'Что ты покупаешь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e017', russian: 'продавать', german: 'verkaufen', ipa: '[fɛɐ̯ˈkaʊ̯fən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich verkaufe mein Auto.', ru: 'Я продаю свою машину.' }, { de: 'Er verkauft Bücher.', ru: 'Он продаёт книги.' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e018', russian: 'приходить', german: 'kommen', ipa: '[ˈkɔmən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich komme aus Russland.', ru: 'Я из России.' }, { de: 'Kommst du heute?', ru: 'Ты придёшь сегодня?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e019', russian: 'жить', german: 'wohnen', ipa: '[ˈvoːnən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich wohne in Berlin.', ru: 'Я живу в Берлине.' }, { de: 'Wo wohnst du?', ru: 'Где ты живёшь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e020', russian: 'спать', german: 'schlafen', ipa: '[ˈʃlaːfən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich schlafe gut.', ru: 'Я хорошо сплю.' }, { de: 'Das Kind schläft.', ru: 'Ребёнок спит.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e021', russian: 'играть', german: 'spielen', ipa: '[ˈʃpiːlən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Die Kinder spielen.', ru: 'Дети играют.' }, { de: 'Ich spiele Gitarre.', ru: 'Я играю на гитаре.' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e022', russian: 'слушать', german: 'hören', ipa: '[ˈhøːʁən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich höre Musik.', ru: 'Я слушаю музыку.' }, { de: 'Hörst du mich?', ru: 'Ты меня слышишь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e023', russian: 'видеть', german: 'sehen', ipa: '[ˈzeːən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich sehe das Haus.', ru: 'Я вижу дом.' }, { de: 'Siehst du das?', ru: 'Ты это видишь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e024', russian: 'думать', german: 'denken', ipa: '[ˈdɛŋkən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich denke, das ist richtig.', ru: 'Я думаю, это правильно.' }, { de: 'Was denkst du?', ru: 'Что ты думаешь?' }], category: 'Базовые глаголы', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e025', russian: 'хотеть', german: 'wollen', ipa: '[ˈvɔlən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich will Deutsch lernen.', ru: 'Я хочу учить немецкий.' }, { de: 'Was willst du?', ru: 'Что ты хочешь?' }], category: 'Базовые глаголы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Adjektive A2-B1
  { id: 'e026', russian: 'красивый', german: 'schön', ipa: '[ʃøːn]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist schön!', ru: 'Это красиво!' }, { de: 'Sie ist sehr schön.', ru: 'Она очень красивая.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e027', russian: 'быстрый', german: 'schnell', ipa: '[ʃnɛl]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Auto ist schnell.', ru: 'Машина быстрая.' }, { de: 'Ich laufe schnell.', ru: 'Я бегу быстро.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e028', russian: 'медленный', german: 'langsam', ipa: '[ˈlaŋzaːm]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Bitte sprich langsam!', ru: 'Пожалуйста, говори медленно!' }, { de: 'Der Zug ist langsam.', ru: 'Поезд медленный.' }], category: 'Прилагательные', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e029', russian: 'дорогой', german: 'teuer', ipa: '[ˈtɔʏ̯ɐ]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist sehr teuer.', ru: 'Это очень дорого.' }, { de: 'Das Auto ist teuer.', ru: 'Машина дорогая.' }], category: 'Прилагательные', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e030', russian: 'дешёвый', german: 'billig', ipa: '[ˈbɪlɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist billig.', ru: 'Это дёшево.' }, { de: 'Ich kaufe billige Sachen.', ru: 'Я покупаю дешёвые вещи.' }], category: 'Прилагательные', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e031', russian: 'тяжёлый', german: 'schwer', ipa: '[ʃveːɐ̯]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Der Koffer ist schwer.', ru: 'Чемодан тяжёлый.' }, { de: 'Das ist schwer für mich.', ru: 'Это трудно для меня.' }], category: 'Прилагательные', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e032', russian: 'лёгкий', german: 'leicht', ipa: '[laɪ̯çt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist leicht.', ru: 'Это лёгкое.' }, { de: 'Die Aufgabe ist leicht.', ru: 'Задание лёгкое.' }], category: 'Прилагательные', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // Nummern (Числа продолжение)
  { id: 'e033', russian: 'четыре', german: 'vier', ipa: '[fiːɐ̯]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe vier Geschwister.', ru: 'У меня четыре брата и сестры.' }, { de: 'Es ist vier Uhr.', ru: 'Сейчас четыре часа.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e034', russian: 'пять', german: 'fünf', ipa: '[fʏnf]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe fünf Finger.', ru: 'У меня пять пальцев.' }, { de: 'Es ist fünf Uhr.', ru: 'Сейчас пять часов.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e035', russian: 'десять', german: 'zehn', ipa: '[tseːn]', partOfSpeech: 'noun', gender: null, examples: [{ de: 'Ich habe zehn Euro.', ru: 'У меня десять евро.' }, { de: 'Es ist zehn Uhr.', ru: 'Сейчас десять часов.' }], category: 'Числа', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Wochentage (Дни недели)
  { id: 'e036', russian: 'понедельник', german: 'der Montag', ipa: '[ˈmoːntaːk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Heute ist Montag.', ru: 'Сегодня понедельник.' }, { de: 'Am Montag gehe ich zur Arbeit.', ru: 'В понедельник я иду на работу.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e037', russian: 'пятница', german: 'der Freitag', ipa: '[ˈfʁaɪ̯taːk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Am Freitag gehe ich ins Kino.', ru: 'В пятницу я иду в кино.' }, { de: 'Freitag ist mein Lieblingstag.', ru: 'Пятница — мой любимый день.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'e038', russian: 'воскресенье', german: 'der Sonntag', ipa: '[ˈzɔntaːk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Am Sonntag schlafe ich lange.', ru: 'В воскресенье я долго сплю.' }, { de: 'Sonntag ist ein Ruhetag.', ru: 'Воскресенье — день отдыха.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // Monate (Месяцы)
  { id: 'e039', russian: 'январь', german: 'der Januar', ipa: '[ˈjanuaːɐ̯]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Im Januar ist es kalt.', ru: 'В январе холодно.' }, { de: 'Mein Geburtstag ist im Januar.', ru: 'Мой день рождения в январе.' }], category: 'Время', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'e040', russian: 'декабрь', german: 'der Dezember', ipa: '[deˈtsɛmbɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Im Dezember gibt es Weihnachten.', ru: 'В декабре Рождество.' }, { de: 'Der Dezember ist der letzte Monat.', ru: 'Декабрь — последний месяц.' }], category: 'Время', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // B1 Verben
  { id: 'e041', russian: 'объяснять', german: 'beschreiben', ipa: '[bəˈʃʁaɪ̯bən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Kannst du das beschreiben?', ru: 'Ты можешь это описать?' }, { de: 'Ich beschreibe mein Haus.', ru: 'Я описываю свой дом.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'e042', russian: 'сравнивать', german: 'vergleichen', ipa: '[fɛɐ̯ˈɡlaɪ̯çən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich vergleiche die Preise.', ru: 'Я сравниваю цены.' }, { de: 'Vergleich die beiden Texte.', ru: 'Сравни оба текста.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'e043', russian: 'предлагать', german: 'vorschlagen', ipa: '[ˈfoːɐ̯ʃlaːɡən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich schlage vor, ins Kino zu gehen.', ru: 'Я предлагаю пойти в кино.' }, { de: 'Was schlägst du vor?', ru: 'Что ты предлагаешь?' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // B2 Adjektive
  { id: 'e044', russian: 'значительный', german: 'bedeutend', ipa: '[bəˈdɔʏ̯tənt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist eine bedeutende Entscheidung.', ru: 'Это значительное решение.' }, { de: 'Er ist ein bedeutender Wissenschaftler.', ru: 'Он значительный учёный.' }], category: 'Прилагательные', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'e045', russian: 'неизбежный', german: 'unvermeidlich', ipa: '[ʊnfɛɐ̯ˈmaɪ̯tlɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist unvermeidlich.', ru: 'Это неизбежно.' }, { de: 'Der Fehler war unvermeidlich.', ru: 'Ошибка была неизбежна.' }], category: 'Прилагательные', difficulty: 5, minUserLevel: 'advanced', cefrLevel: 'B2' },

  // Phrasen (Фразы)
  { id: 'p001', russian: 'пожалуйста', german: 'bitte', ipa: '[ˈbɪtə]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Bitte hilf mir!', ru: 'Пожалуйста, помоги мне!' }, { de: 'Danke! — Bitte!', ru: 'Спасибо! — Пожалуйста!' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'p002', russian: 'спасибо', german: 'danke', ipa: '[ˈdaŋkə]', partOfSpeech: 'adverb', gender: null, examples: [{ de: 'Danke schön!', ru: 'Большое спасибо!' }, { de: 'Vielen Dank!', ru: 'Большое спасибо!' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'p003', russian: 'извините', german: 'Entschuldigung', ipa: '[ɛntˈʃʊldɪɡʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Entschuldigung, wo ist der Bahnhof?', ru: 'Извините, где вокзал?' }, { de: 'Entschuldigung, ich bin zu spät.', ru: 'Извините, я опоздал.' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'p004', russian: 'привет', german: 'Hallo', ipa: '[haˈloː]', partOfSpeech: 'phrase', gender: null, examples: [{ de: 'Hallo! Wie geht es dir?', ru: 'Привет! Как дела?' }, { de: 'Hallo, ich bin Max.', ru: 'Привет, я Макс.' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'p005', russian: 'до свидания', german: 'Auf Wiedersehen', ipa: '[aʊ̯f ˈviːdɐzeːən]', partOfSpeech: 'phrase', gender: null, examples: [{ de: 'Auf Wiedersehen!', ru: 'До свидания!' }, { de: 'Tschüss! / Auf Wiedersehen!', ru: 'Пока! / До свидания!' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'p006', russian: 'как дела?', german: 'Wie geht es Ihnen?', ipa: '[viː ɡeːt ɛs ˈiːnən]', partOfSpeech: 'phrase', gender: null, examples: [{ de: 'Wie geht es Ihnen? — Danke, gut.', ru: 'Как дела? — Спасибо, хорошо.' }, { de: 'Wie geht es dir?', ru: 'Как у тебя дела?' }], category: 'Фразы', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
];

// ─── Erweiterung: 350+ neue Wörter A1–B2 ────────────────────────────────────

const vocabularyDataNew: Word[] = [
  // ── A1: Alltag & Haus ──────────────────────────────────────────────────────
  { id: 'x001', russian: 'дом', german: 'das Haus', ipa: '[haʊ̯s]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich wohne in einem Haus.', ru: 'Я живу в доме.' }, { de: 'Das Haus ist groß.', ru: 'Дом большой.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x002', russian: 'квартира', german: 'die Wohnung', ipa: '[ˈvoːnʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Wohnung ist klein.', ru: 'Моя квартира маленькая.' }, { de: 'Ich suche eine Wohnung.', ru: 'Я ищу квартиру.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x003', russian: 'комната', german: 'das Zimmer', ipa: '[ˈtsɪmɐ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Mein Zimmer ist ordentlich.', ru: 'Моя комната аккуратная.' }, { de: 'Das Zimmer hat zwei Fenster.', ru: 'В комнате два окна.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x004', russian: 'кухня', german: 'die Küche', ipa: '[ˈkʏçə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich koche in der Küche.', ru: 'Я готовлю на кухне.' }, { de: 'Die Küche ist modern.', ru: 'Кухня современная.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x005', russian: 'ванная', german: 'das Badezimmer', ipa: '[ˈbaːdəˌtsɪmɐ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Badezimmer ist sauber.', ru: 'Ванная чистая.' }, { de: 'Ich dusche im Badezimmer.', ru: 'Я принимаю душ в ванной.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x006', russian: 'стол', german: 'der Tisch', ipa: '[tɪʃ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Das Buch liegt auf dem Tisch.', ru: 'Книга лежит на столе.' }, { de: 'Wir essen am Tisch.', ru: 'Мы едим за столом.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x007', russian: 'стул', german: 'der Stuhl', ipa: '[ʃtuːl]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Setz dich auf den Stuhl!', ru: 'Сядь на стул!' }, { de: 'Der Stuhl ist bequem.', ru: 'Стул удобный.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x008', russian: 'кровать', german: 'das Bett', ipa: '[bɛt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich schlafe im Bett.', ru: 'Я сплю в кровати.' }, { de: 'Das Bett ist weich.', ru: 'Кровать мягкая.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x009', russian: 'окно', german: 'das Fenster', ipa: '[ˈfɛnstɐ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Öffne das Fenster!', ru: 'Открой окно!' }, { de: 'Das Fenster ist kaputt.', ru: 'Окно сломано.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x010', russian: 'дверь', german: 'die Tür', ipa: '[tyːɐ̯]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Mach die Tür zu!', ru: 'Закрой дверь!' }, { de: 'Die Tür ist offen.', ru: 'Дверь открыта.' }], category: 'Дом', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // ── A1: Еда и напитки ──────────────────────────────────────────────────────
  { id: 'x011', russian: 'хлеб', german: 'das Brot', ipa: '[bʁoːt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich esse Brot zum Frühstück.', ru: 'Я ем хлеб на завтрак.' }, { de: 'Das Brot ist frisch.', ru: 'Хлеб свежий.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x012', russian: 'молоко', german: 'die Milch', ipa: '[mɪlç]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich trinke Milch.', ru: 'Я пью молоко.' }, { de: 'Die Milch ist kalt.', ru: 'Молоко холодное.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x013', russian: 'яйцо', german: 'das Ei', ipa: '[aɪ̯]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich esse ein Ei.', ru: 'Я ем яйцо.' }, { de: 'Zwei Eier, bitte.', ru: 'Два яйца, пожалуйста.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x014', russian: 'мясо', german: 'das Fleisch', ipa: '[flaɪ̯ʃ]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich esse kein Fleisch.', ru: 'Я не ем мясо.' }, { de: 'Das Fleisch ist lecker.', ru: 'Мясо вкусное.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x015', russian: 'рыба', german: 'der Fisch', ipa: '[fɪʃ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich esse gerne Fisch.', ru: 'Я люблю есть рыбу.' }, { de: 'Der Fisch ist frisch.', ru: 'Рыба свежая.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x016', russian: 'суп', german: 'die Suppe', ipa: '[ˈzʊpə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Suppe ist heiß.', ru: 'Суп горячий.' }, { de: 'Ich koche eine Suppe.', ru: 'Я варю суп.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x017', russian: 'сыр', german: 'der Käse', ipa: '[ˈkɛːzə]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich mag Käse.', ru: 'Я люблю сыр.' }, { de: 'Der Käse ist lecker.', ru: 'Сыр вкусный.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x018', russian: 'масло', german: 'die Butter', ipa: '[ˈbʊtɐ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich streiche Butter aufs Brot.', ru: 'Я намазываю масло на хлеб.' }, { de: 'Die Butter ist weich.', ru: 'Масло мягкое.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x019', russian: 'сахар', german: 'der Zucker', ipa: '[ˈtsʊkɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich nehme keinen Zucker.', ru: 'Я не беру сахар.' }, { de: 'Der Kaffee ist ohne Zucker.', ru: 'Кофе без сахара.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x020', russian: 'соль', german: 'das Salz', ipa: '[zalts]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Gib mir das Salz, bitte.', ru: 'Дай мне соль, пожалуйста.' }, { de: 'Das Essen braucht Salz.', ru: 'Еде нужна соль.' }], category: 'Еда', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // ── A1: Тело ───────────────────────────────────────────────────────────────
  { id: 'x021', russian: 'голова', german: 'der Kopf', ipa: '[kɔpf]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Mein Kopf tut weh.', ru: 'У меня болит голова.' }, { de: 'Er nickt mit dem Kopf.', ru: 'Он кивает головой.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x022', russian: 'рука', german: 'die Hand', ipa: '[hant]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Gib mir deine Hand!', ru: 'Дай мне руку!' }, { de: 'Meine Hände sind kalt.', ru: 'Мои руки холодные.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x023', russian: 'нога', german: 'das Bein', ipa: '[baɪ̯n]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Mein Bein tut weh.', ru: 'У меня болит нога.' }, { de: 'Er hat lange Beine.', ru: 'У него длинные ноги.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x024', russian: 'глаз', german: 'das Auge', ipa: '[ˈaʊ̯ɡə]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Sie hat blaue Augen.', ru: 'У неё голубые глаза.' }, { de: 'Meine Augen sind müde.', ru: 'Мои глаза устали.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x025', russian: 'ухо', german: 'das Ohr', ipa: '[oːɐ̯]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Mein Ohr tut weh.', ru: 'У меня болит ухо.' }, { de: 'Er hört mit den Ohren.', ru: 'Он слышит ушами.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x026', russian: 'нос', german: 'die Nase', ipa: '[ˈnaːzə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Meine Nase läuft.', ru: 'У меня течёт нос.' }, { de: 'Er hat eine große Nase.', ru: 'У него большой нос.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x027', russian: 'рот', german: 'der Mund', ipa: '[mʊnt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Öffne den Mund!', ru: 'Открой рот!' }, { de: 'Er lacht mit dem Mund.', ru: 'Он смеётся ртом.' }], category: 'Тело', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // ── A1: Цвета ──────────────────────────────────────────────────────────────
  { id: 'x028', russian: 'красный', german: 'rot', ipa: '[ʁoːt]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Auto ist rot.', ru: 'Машина красная.' }, { de: 'Ich mag die rote Farbe.', ru: 'Мне нравится красный цвет.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x029', russian: 'синий', german: 'blau', ipa: '[blaʊ̯]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Der Himmel ist blau.', ru: 'Небо синее.' }, { de: 'Sie trägt ein blaues Kleid.', ru: 'Она носит синее платье.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x030', russian: 'зелёный', german: 'grün', ipa: '[ɡʁyːn]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das Gras ist grün.', ru: 'Трава зелёная.' }, { de: 'Er mag grüne Äpfel.', ru: 'Он любит зелёные яблоки.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x031', russian: 'жёлтый', german: 'gelb', ipa: '[ɡɛlp]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Die Sonne ist gelb.', ru: 'Солнце жёлтое.' }, { de: 'Die Banane ist gelb.', ru: 'Банан жёлтый.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x032', russian: 'чёрный', german: 'schwarz', ipa: '[ʃvaʁts]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Die Katze ist schwarz.', ru: 'Кошка чёрная.' }, { de: 'Er trägt schwarze Schuhe.', ru: 'Он носит чёрные туфли.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x033', russian: 'белый', german: 'weiß', ipa: '[vaɪ̯s]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Der Schnee ist weiß.', ru: 'Снег белый.' }, { de: 'Sie trägt ein weißes Hemd.', ru: 'Она носит белую рубашку.' }], category: 'Цвета', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // ── A1: Числа и время ──────────────────────────────────────────────────────
  { id: 'x034', russian: 'час', german: 'die Stunde', ipa: '[ˈʃtʊndə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich warte eine Stunde.', ru: 'Я жду один час.' }, { de: 'In einer Stunde bin ich fertig.', ru: 'Через час я закончу.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x035', russian: 'минута', german: 'die Minute', ipa: '[mɪˈnuːtə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Warte fünf Minuten!', ru: 'Подожди пять минут!' }, { de: 'In zehn Minuten komme ich.', ru: 'Через десять минут я приду.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x036', russian: 'утро', german: 'der Morgen', ipa: '[ˈmɔʁɡən]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Guten Morgen!', ru: 'Доброе утро!' }, { de: 'Am Morgen trinke ich Kaffee.', ru: 'Утром я пью кофе.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x037', russian: 'вечер', german: 'der Abend', ipa: '[ˈaːbənt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Guten Abend!', ru: 'Добрый вечер!' }, { de: 'Am Abend lese ich.', ru: 'Вечером я читаю.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },
  { id: 'x038', russian: 'ночь', german: 'die Nacht', ipa: '[naxt]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Gute Nacht!', ru: 'Спокойной ночи!' }, { de: 'In der Nacht schlafe ich.', ru: 'Ночью я сплю.' }], category: 'Время', difficulty: 1, minUserLevel: 'beginner', cefrLevel: 'A1' },

  // ── A2: Транспорт ──────────────────────────────────────────────────────────
  { id: 'x039', russian: 'поезд', german: 'der Zug', ipa: '[tsuːk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Zug fährt um 9 Uhr ab.', ru: 'Поезд отправляется в 9 часов.' }, { de: 'Ich fahre mit dem Zug.', ru: 'Я еду на поезде.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x040', russian: 'автобус', german: 'der Bus', ipa: '[bʊs]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich nehme den Bus.', ru: 'Я сажусь на автобус.' }, { de: 'Der Bus kommt in 5 Minuten.', ru: 'Автобус придёт через 5 минут.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x041', russian: 'самолёт', german: 'das Flugzeug', ipa: '[ˈfluːkˌtsɔʏ̯k]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Flugzeug landet um 14 Uhr.', ru: 'Самолёт приземляется в 14 часов.' }, { de: 'Ich fliege mit dem Flugzeug.', ru: 'Я лечу на самолёте.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x042', russian: 'велосипед', german: 'das Fahrrad', ipa: '[ˈfaːɐ̯ˌʁaːt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich fahre Fahrrad.', ru: 'Я езжу на велосипеде.' }, { de: 'Das Fahrrad ist kaputt.', ru: 'Велосипед сломан.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x043', russian: 'вокзал', german: 'der Bahnhof', ipa: '[ˈbaːnhoːf]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Wo ist der Bahnhof?', ru: 'Где вокзал?' }, { de: 'Ich warte am Bahnhof.', ru: 'Я жду на вокзале.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x044', russian: 'аэропорт', german: 'der Flughafen', ipa: '[ˈfluːkˌhaːfən]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich fahre zum Flughafen.', ru: 'Я еду в аэропорт.' }, { de: 'Der Flughafen ist weit.', ru: 'Аэропорт далеко.' }], category: 'Транспорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── A2: Профессии ──────────────────────────────────────────────────────────
  { id: 'x045', russian: 'учитель', german: 'der Lehrer', ipa: '[ˈleːʁɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Lehrer erklärt die Grammatik.', ru: 'Учитель объясняет грамматику.' }, { de: 'Mein Lehrer ist nett.', ru: 'Мой учитель добрый.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x046', russian: 'врач', german: 'der Arzt', ipa: '[aːɐ̯tst]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich gehe zum Arzt.', ru: 'Я иду к врачу.' }, { de: 'Der Arzt ist freundlich.', ru: 'Врач дружелюбный.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x047', russian: 'инженер', german: 'der Ingenieur', ipa: '[ɪnʒeˈnjøːɐ̯]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Er ist Ingenieur.', ru: 'Он инженер.' }, { de: 'Die Ingenieurin baut Brücken.', ru: 'Инженер строит мосты.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x048', russian: 'повар', german: 'der Koch', ipa: '[kɔx]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Koch kocht leckeres Essen.', ru: 'Повар готовит вкусную еду.' }, { de: 'Ich bin kein Koch.', ru: 'Я не повар.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x049', russian: 'полицейский', german: 'der Polizist', ipa: '[poliˈtsɪst]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Polizist hilft mir.', ru: 'Полицейский помогает мне.' }, { de: 'Ich sehe einen Polizisten.', ru: 'Я вижу полицейского.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x050', russian: 'продавец', german: 'der Verkäufer', ipa: '[fɛɐ̯ˈkɔʏ̯fɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Verkäufer ist freundlich.', ru: 'Продавец дружелюбный.' }, { de: 'Ich frage den Verkäufer.', ru: 'Я спрашиваю продавца.' }], category: 'Профессии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── A2: Природа и погода ───────────────────────────────────────────────────
  { id: 'x051', russian: 'дождь', german: 'der Regen', ipa: '[ˈʁeːɡən]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Es regnet heute.', ru: 'Сегодня идёт дождь.' }, { de: 'Der Regen ist stark.', ru: 'Дождь сильный.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x052', russian: 'снег', german: 'der Schnee', ipa: '[ʃneː]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Es schneit.', ru: 'Идёт снег.' }, { de: 'Der Schnee ist weiß.', ru: 'Снег белый.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x053', russian: 'ветер', german: 'der Wind', ipa: '[vɪnt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Wind ist stark.', ru: 'Ветер сильный.' }, { de: 'Es ist windig heute.', ru: 'Сегодня ветрено.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x054', russian: 'облако', german: 'die Wolke', ipa: '[ˈvɔlkə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Wolken sind dunkel.', ru: 'Облака тёмные.' }, { de: 'Es gibt viele Wolken.', ru: 'Много облаков.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x055', russian: 'река', german: 'der Fluss', ipa: '[flʊs]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Fluss ist breit.', ru: 'Река широкая.' }, { de: 'Wir schwimmen im Fluss.', ru: 'Мы купаемся в реке.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x056', russian: 'море', german: 'das Meer', ipa: '[meːɐ̯]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das Meer ist blau.', ru: 'Море синее.' }, { de: 'Wir fahren ans Meer.', ru: 'Мы едем к морю.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x057', russian: 'гора', german: 'der Berg', ipa: '[bɛʁk]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Berg ist hoch.', ru: 'Гора высокая.' }, { de: 'Wir wandern in den Bergen.', ru: 'Мы ходим в горы.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x058', russian: 'лес', german: 'der Wald', ipa: '[valt]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Wir gehen in den Wald.', ru: 'Мы идём в лес.' }, { de: 'Der Wald ist grün.', ru: 'Лес зелёный.' }], category: 'Природа', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── B1: Глаголы ────────────────────────────────────────────────────────────
  { id: 'x059', russian: 'решать', german: 'entscheiden', ipa: '[ɛntˈʃaɪ̯dən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich muss mich entscheiden.', ru: 'Мне нужно решить.' }, { de: 'Wir entscheiden gemeinsam.', ru: 'Мы решаем вместе.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x060', russian: 'продолжать', german: 'weitermachen', ipa: '[ˈvaɪ̯tɐˌmaxən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Mach weiter!', ru: 'Продолжай!' }, { de: 'Wir machen weiter.', ru: 'Мы продолжаем.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x061', russian: 'заканчивать', german: 'beenden', ipa: '[bəˈɛndən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich beende die Arbeit.', ru: 'Я заканчиваю работу.' }, { de: 'Wann beendest du das Projekt?', ru: 'Когда ты закончишь проект?' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x062', russian: 'изменять', german: 'ändern', ipa: '[ˈɛndɐn]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich ändere meine Meinung.', ru: 'Я меняю своё мнение.' }, { de: 'Das ändert nichts.', ru: 'Это ничего не меняет.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x063', russian: 'достигать', german: 'erreichen', ipa: '[ɛɐ̯ˈʁaɪ̯çən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich erreiche mein Ziel.', ru: 'Я достигаю своей цели.' }, { de: 'Wir haben es erreicht!', ru: 'Мы этого достигли!' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x064', russian: 'улучшать', german: 'verbessern', ipa: '[fɛɐ̯ˈbɛsɐn]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich verbessere mein Deutsch.', ru: 'Я улучшаю свой немецкий.' }, { de: 'Wir verbessern den Prozess.', ru: 'Мы улучшаем процесс.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x065', russian: 'уменьшать', german: 'reduzieren', ipa: '[ʁeduˈtsiːʁən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Wir reduzieren die Kosten.', ru: 'Мы сокращаем расходы.' }, { de: 'Ich reduziere meinen Konsum.', ru: 'Я сокращаю потребление.' }], category: 'Базовые глаголы', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // ── B1: Прилагательные ─────────────────────────────────────────────────────
  { id: 'x066', russian: 'необходимый', german: 'notwendig', ipa: '[ˈnoːtvɛndɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist notwendig.', ru: 'Это необходимо.' }, { de: 'Eine Pause ist notwendig.', ru: 'Перерыв необходим.' }], category: 'Прилагательные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x067', russian: 'возможный', german: 'möglich', ipa: '[ˈmøːklɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist möglich.', ru: 'Это возможно.' }, { de: 'Ist das möglich?', ru: 'Это возможно?' }], category: 'Прилагательные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x068', russian: 'невозможный', german: 'unmöglich', ipa: '[ʊnˈmøːklɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist unmöglich!', ru: 'Это невозможно!' }, { de: 'Es scheint unmöglich.', ru: 'Кажется невозможным.' }], category: 'Прилагательные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x069', russian: 'ответственный', german: 'verantwortlich', ipa: '[fɛɐ̯ˈantvɔʁtlɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Er ist verantwortlich.', ru: 'Он ответственный.' }, { de: 'Wer ist verantwortlich?', ru: 'Кто несёт ответственность?' }], category: 'Прилагательные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x070', russian: 'удивительный', german: 'erstaunlich', ipa: '[ɛɐ̯ˈʃtaʊ̯nlɪç]', partOfSpeech: 'adjective', gender: null, examples: [{ de: 'Das ist erstaunlich!', ru: 'Это удивительно!' }, { de: 'Eine erstaunliche Leistung.', ru: 'Удивительное достижение.' }], category: 'Прилагательные', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // ── B1: Абстрактные существительные ───────────────────────────────────────
  { id: 'x071', russian: 'опыт', german: 'die Erfahrung', ipa: '[ɛɐ̯ˈfaːʁʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich habe Erfahrung.', ru: 'У меня есть опыт.' }, { de: 'Das ist eine neue Erfahrung.', ru: 'Это новый опыт.' }], category: 'Абстрактные понятия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x072', russian: 'возможность', german: 'die Möglichkeit', ipa: '[ˈmøːklɪçkaɪ̯t]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Das ist eine gute Möglichkeit.', ru: 'Это хорошая возможность.' }, { de: 'Ich habe keine Möglichkeit.', ru: 'У меня нет возможности.' }], category: 'Абстрактные понятия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x073', russian: 'решение', german: 'die Entscheidung', ipa: '[ɛntˈʃaɪ̯dʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Das ist eine schwere Entscheidung.', ru: 'Это трудное решение.' }, { de: 'Ich treffe eine Entscheidung.', ru: 'Я принимаю решение.' }], category: 'Абстрактные понятия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x074', russian: 'проблема', german: 'das Problem', ipa: '[pʁoˈbleːm]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Das ist ein Problem.', ru: 'Это проблема.' }, { de: 'Wir lösen das Problem.', ru: 'Мы решаем проблему.' }], category: 'Абстрактные понятия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x075', russian: 'цель', german: 'das Ziel', ipa: '[tsiːl]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Mein Ziel ist es, Deutsch zu lernen.', ru: 'Моя цель — выучить немецкий.' }, { de: 'Wir erreichen unser Ziel.', ru: 'Мы достигаем своей цели.' }], category: 'Абстрактные понятия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // ── B2: Сложные глаголы ────────────────────────────────────────────────────
  { id: 'x076', russian: 'осознавать', german: 'erkennen', ipa: '[ɛɐ̯ˈkɛnən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich erkenne das Problem.', ru: 'Я осознаю проблему.' }, { de: 'Er hat es erkannt.', ru: 'Он это осознал.' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x077', russian: 'предполагать', german: 'annehmen', ipa: '[ˈanneːmən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich nehme an, dass er kommt.', ru: 'Я предполагаю, что он придёт.' }, { de: 'Was nimmst du an?', ru: 'Что ты предполагаешь?' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x078', russian: 'оценивать', german: 'bewerten', ipa: '[bəˈveːɐ̯tən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich bewerte die Situation.', ru: 'Я оцениваю ситуацию.' }, { de: 'Wie bewertest du das?', ru: 'Как ты это оцениваешь?' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x079', russian: 'реализовывать', german: 'verwirklichen', ipa: '[fɛɐ̯ˈvɪʁklɪçən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich verwirkliche meinen Traum.', ru: 'Я реализую свою мечту.' }, { de: 'Wir verwirklichen das Projekt.', ru: 'Мы реализуем проект.' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x080', russian: 'подчёркивать', german: 'betonen', ipa: '[bəˈtoːnən]', partOfSpeech: 'verb', gender: null, examples: [{ de: 'Ich betone die Wichtigkeit.', ru: 'Я подчёркиваю важность.' }, { de: 'Er betont jedes Wort.', ru: 'Он подчёркивает каждое слово.' }], category: 'Базовые глаголы', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },

  // ── B2: Абстрактные существительные ───────────────────────────────────────
  { id: 'x081', russian: 'последствие', german: 'die Konsequenz', ipa: '[kɔnzeˈkvɛnts]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Das hat Konsequenzen.', ru: 'Это имеет последствия.' }, { de: 'Die Konsequenzen sind klar.', ru: 'Последствия ясны.' }], category: 'Абстрактные понятия', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x082', russian: 'обстоятельство', german: 'der Umstand', ipa: '[ˈʊmʃtant]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Unter diesen Umständen...', ru: 'При этих обстоятельствах...' }, { de: 'Die Umstände sind schwierig.', ru: 'Обстоятельства сложные.' }], category: 'Абстрактные понятия', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x083', russian: 'перспектива', german: 'die Perspektive', ipa: '[pɛʁspɛkˈtiːvə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich sehe es aus einer anderen Perspektive.', ru: 'Я вижу это с другой перспективы.' }, { de: 'Die Perspektive ändert sich.', ru: 'Перспектива меняется.' }], category: 'Абстрактные понятия', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x084', russian: 'противоречие', german: 'der Widerspruch', ipa: '[ˈviːdɐˌʃpʁʊx]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Das ist ein Widerspruch.', ru: 'Это противоречие.' }, { de: 'Kein Widerspruch!', ru: 'Никаких противоречий!' }], category: 'Абстрактные понятия', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x085', russian: 'влияние', german: 'der Einfluss', ipa: '[ˈaɪ̯nflʊs]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Er hat großen Einfluss.', ru: 'Он имеет большое влияние.' }, { de: 'Der Einfluss ist stark.', ru: 'Влияние сильное.' }], category: 'Абстрактные понятия', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },

  // ── A2: Магазин и деньги ───────────────────────────────────────────────────
  { id: 'x086', russian: 'деньги', german: 'das Geld', ipa: '[ɡɛlt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich habe kein Geld.', ru: 'У меня нет денег.' }, { de: 'Das kostet viel Geld.', ru: 'Это стоит много денег.' }], category: 'Магазин', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x087', russian: 'цена', german: 'der Preis', ipa: '[pʁaɪ̯s]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Was kostet das? — Der Preis ist 10 Euro.', ru: 'Сколько это стоит? — Цена 10 евро.' }, { de: 'Der Preis ist hoch.', ru: 'Цена высокая.' }], category: 'Магазин', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x088', russian: 'скидка', german: 'der Rabatt', ipa: '[ʁaˈbat]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Gibt es einen Rabatt?', ru: 'Есть скидка?' }, { de: 'Ich bekomme 10% Rabatt.', ru: 'Я получаю скидку 10%.' }], category: 'Магазин', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x089', russian: 'касса', german: 'die Kasse', ipa: '[ˈkasə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Wo ist die Kasse?', ru: 'Где касса?' }, { de: 'Ich zahle an der Kasse.', ru: 'Я плачу на кассе.' }], category: 'Магазин', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x090', russian: 'чек', german: 'der Kassenbon', ipa: '[ˈkasənbɔn]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Kann ich den Kassenbon haben?', ru: 'Можно мне чек?' }, { de: 'Der Kassenbon ist wichtig.', ru: 'Чек важен.' }], category: 'Магазин', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── B1: Образование ────────────────────────────────────────────────────────
  { id: 'x091', russian: 'университет', german: 'die Universität', ipa: '[ʊnivɛʁziˈtɛːt]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich studiere an der Universität.', ru: 'Я учусь в университете.' }, { de: 'Die Universität ist groß.', ru: 'Университет большой.' }], category: 'Образование', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x092', russian: 'экзамен', german: 'die Prüfung', ipa: '[ˈpʁyːfʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich lerne für die Prüfung.', ru: 'Я учусь к экзамену.' }, { de: 'Die Prüfung ist schwer.', ru: 'Экзамен сложный.' }], category: 'Образование', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x093', russian: 'диплом', german: 'das Diplom', ipa: '[diˈploːm]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich habe mein Diplom bekommen.', ru: 'Я получил диплом.' }, { de: 'Das Diplom ist wichtig.', ru: 'Диплом важен.' }], category: 'Образование', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x094', russian: 'курс', german: 'der Kurs', ipa: '[kʊʁs]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich mache einen Deutschkurs.', ru: 'Я прохожу курс немецкого.' }, { de: 'Der Kurs ist interessant.', ru: 'Курс интересный.' }], category: 'Образование', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x095', russian: 'задание', german: 'die Aufgabe', ipa: '[ˈaʊ̯fɡaːbə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Aufgabe ist schwer.', ru: 'Задание сложное.' }, { de: 'Ich mache meine Aufgaben.', ru: 'Я делаю задания.' }], category: 'Образование', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // ── B1: Здоровье ───────────────────────────────────────────────────────────
  { id: 'x096', russian: 'болезнь', german: 'die Krankheit', ipa: '[ˈkʁaŋkhaɪ̯t]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Krankheit ist ansteckend.', ru: 'Болезнь заразная.' }, { de: 'Er hat eine Krankheit.', ru: 'У него болезнь.' }], category: 'Здоровье', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x097', russian: 'лекарство', german: 'das Medikament', ipa: '[medɪkaˈmɛnt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich nehme ein Medikament.', ru: 'Я принимаю лекарство.' }, { de: 'Das Medikament hilft.', ru: 'Лекарство помогает.' }], category: 'Здоровье', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x098', russian: 'больница', german: 'das Krankenhaus', ipa: '[ˈkʁaŋkənˌhaʊ̯s]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Er liegt im Krankenhaus.', ru: 'Он лежит в больнице.' }, { de: 'Ich fahre ins Krankenhaus.', ru: 'Я еду в больницу.' }], category: 'Здоровье', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x099', russian: 'операция', german: 'die Operation', ipa: '[ɔpeʁaˈtsi̯oːn]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Operation war erfolgreich.', ru: 'Операция прошла успешно.' }, { de: 'Er braucht eine Operation.', ru: 'Ему нужна операция.' }], category: 'Здоровье', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x100', russian: 'аллергия', german: 'die Allergie', ipa: '[alɛʁˈɡiː]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich habe eine Allergie.', ru: 'У меня аллергия.' }, { de: 'Bist du allergisch?', ru: 'Ты аллергик?' }], category: 'Здоровье', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },

  // ── B2: Политика и общество ────────────────────────────────────────────────
  { id: 'x101', russian: 'демократия', german: 'die Demokratie', ipa: '[demoˈkʁaːtiː]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Deutschland ist eine Demokratie.', ru: 'Германия — демократия.' }, { de: 'Die Demokratie ist wichtig.', ru: 'Демократия важна.' }], category: 'Общество', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x102', russian: 'экономика', german: 'die Wirtschaft', ipa: '[ˈvɪʁtʃaft]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Wirtschaft wächst.', ru: 'Экономика растёт.' }, { de: 'Die Wirtschaft ist stark.', ru: 'Экономика сильная.' }], category: 'Общество', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x103', russian: 'окружающая среда', german: 'die Umwelt', ipa: '[ˈʊmvɛlt]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Wir schützen die Umwelt.', ru: 'Мы защищаем окружающую среду.' }, { de: 'Die Umwelt ist in Gefahr.', ru: 'Окружающая среда под угрозой.' }], category: 'Общество', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x104', russian: 'изменение климата', german: 'der Klimawandel', ipa: '[ˈkliːmaˌvandəl]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Klimawandel ist ein Problem.', ru: 'Изменение климата — проблема.' }, { de: 'Wir bekämpfen den Klimawandel.', ru: 'Мы боремся с изменением климата.' }], category: 'Общество', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },
  { id: 'x105', russian: 'глобализация', german: 'die Globalisierung', ipa: '[ɡlobalizˈiːʁʊŋ]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Die Globalisierung hat Vor- und Nachteile.', ru: 'Глобализация имеет плюсы и минусы.' }, { de: 'Die Globalisierung verändert die Welt.', ru: 'Глобализация меняет мир.' }], category: 'Общество', difficulty: 4, minUserLevel: 'advanced', cefrLevel: 'B2' },

  // ── A2: Спорт и хобби ─────────────────────────────────────────────────────
  { id: 'x106', russian: 'футбол', german: 'der Fußball', ipa: '[ˈfuːsbal]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich spiele Fußball.', ru: 'Я играю в футбол.' }, { de: 'Fußball ist mein Hobby.', ru: 'Футбол — моё хобби.' }], category: 'Спорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x107', russian: 'плавание', german: 'das Schwimmen', ipa: '[ˈʃvɪmən]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich gehe schwimmen.', ru: 'Я иду плавать.' }, { de: 'Schwimmen ist gesund.', ru: 'Плавание полезно.' }], category: 'Спорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x108', russian: 'бег', german: 'das Laufen', ipa: '[ˈlaʊ̯fən]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich gehe laufen.', ru: 'Я иду бегать.' }, { de: 'Laufen macht Spaß.', ru: 'Бег — это весело.' }], category: 'Спорт', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x109', russian: 'музыка', german: 'die Musik', ipa: '[muˈziːk]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich höre gerne Musik.', ru: 'Я люблю слушать музыку.' }, { de: 'Musik macht mich glücklich.', ru: 'Музыка делает меня счастливым.' }], category: 'Хобби', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x110', russian: 'рисование', german: 'das Zeichnen', ipa: '[ˈtsaɪ̯çnən]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich zeichne gerne.', ru: 'Я люблю рисовать.' }, { de: 'Zeichnen ist kreativ.', ru: 'Рисование — творческое занятие.' }], category: 'Хобби', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── A2: Технологии ─────────────────────────────────────────────────────────
  { id: 'x111', russian: 'компьютер', german: 'der Computer', ipa: '[kɔmˈpjuːtɐ]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich arbeite am Computer.', ru: 'Я работаю за компьютером.' }, { de: 'Der Computer ist neu.', ru: 'Компьютер новый.' }], category: 'Технологии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x112', russian: 'интернет', german: 'das Internet', ipa: '[ˈɪntɐnɛt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich surfe im Internet.', ru: 'Я сижу в интернете.' }, { de: 'Das Internet ist langsam.', ru: 'Интернет медленный.' }], category: 'Технологии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x113', russian: 'электронная почта', german: 'die E-Mail', ipa: '[ˈiːmeɪ̯l]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich schreibe eine E-Mail.', ru: 'Я пишу электронное письмо.' }, { de: 'Hast du meine E-Mail bekommen?', ru: 'Ты получил моё письмо?' }], category: 'Технологии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x114', russian: 'приложение', german: 'die App', ipa: '[ɛp]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich lade eine App herunter.', ru: 'Я скачиваю приложение.' }, { de: 'Die App ist kostenlos.', ru: 'Приложение бесплатное.' }], category: 'Технологии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },
  { id: 'x115', russian: 'пароль', german: 'das Passwort', ipa: '[ˈpasvɔʁt]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich vergesse mein Passwort.', ru: 'Я забываю пароль.' }, { de: 'Das Passwort ist sicher.', ru: 'Пароль надёжный.' }], category: 'Технологии', difficulty: 2, minUserLevel: 'beginner', cefrLevel: 'A2' },

  // ── B1: Путешествия ────────────────────────────────────────────────────────
  { id: 'x116', russian: 'паспорт', german: 'der Reisepass', ipa: '[ˈʁaɪ̯zəˌpas]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Ich brauche meinen Reisepass.', ru: 'Мне нужен паспорт.' }, { de: 'Wo ist mein Reisepass?', ru: 'Где мой паспорт?' }], category: 'Путешествия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x117', russian: 'гостиница', german: 'das Hotel', ipa: '[hoˈtɛl]', partOfSpeech: 'noun', gender: 'das', examples: [{ de: 'Ich buche ein Hotel.', ru: 'Я бронирую гостиницу.' }, { de: 'Das Hotel ist komfortabel.', ru: 'Гостиница комфортная.' }], category: 'Путешествия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x118', russian: 'билет', german: 'die Fahrkarte', ipa: '[ˈfaːɐ̯ˌkaʁtə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Ich kaufe eine Fahrkarte.', ru: 'Я покупаю билет.' }, { de: 'Die Fahrkarte kostet 20 Euro.', ru: 'Билет стоит 20 евро.' }], category: 'Путешествия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x119', russian: 'граница', german: 'die Grenze', ipa: '[ˈɡʁɛntsə]', partOfSpeech: 'noun', gender: 'die', examples: [{ de: 'Wir überqueren die Grenze.', ru: 'Мы пересекаем границу.' }, { de: 'Die Grenze ist offen.', ru: 'Граница открыта.' }], category: 'Путешествия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
  { id: 'x120', russian: 'туризм', german: 'der Tourismus', ipa: '[tuˈʁɪsmʊs]', partOfSpeech: 'noun', gender: 'der', examples: [{ de: 'Der Tourismus ist wichtig.', ru: 'Туризм важен.' }, { de: 'Der Tourismus wächst.', ru: 'Туризм растёт.' }], category: 'Путешествия', difficulty: 3, minUserLevel: 'intermediate', cefrLevel: 'B1' },
];

// Merge all extra vocabulary
export const vocabularyDataExtra: Word[] = [...vocabularyDataOld, ...vocabularyDataNew];
